name = "pantrybook-do"
type = "javascript"
workers_dev = true
account_id = "your-account-id"

[build.upload]
dir = "src"
format = "modules"
main = "./worker.mjs"

[durable_objects]
bindings = [
    { name = "UserObject", class_name = "User" }
]

[[migrations]]
tag = "v1"
new_classes = ["User"]