name: Integration Tests

on: push

jobs:
  run-linters:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        run: npm i & npx playwright install

      - name: Run the tests.

        run: npm run test
